version: '3.8'

services:
  # Service PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chatbox_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=chatbox_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./backend:/app

  #Front
  frontend:
    build:
      context: ./chatbox_project_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./chatbox_project_front:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
